const el=id=>document.getElementById(id);
let seriesToken=null,seriesSignature=null;
const seriesLabels={Waiting:'Ожидает следующего запуска',Running:'Серия исполняется',Completed:'Серия завершена',Stopped:'Серия остановлена',InterventionRequired:'Серия требует вмешательства',Disabled:'Расписание выключено',RunCompleted:'Запуск завершён',RunFailed:'Отказ запуска',SeriesCompleted:'Серия завершена',SeriesStopped:'Серия остановлена'};
function seriesReason(reason){return ({SeriesBudgetExhausted:'Исчерпан бюджет серии',SeriesWindowExhausted:'Окончилось окно запуска',InterruptedReservation:'Предыдущий запуск прерван; требуется проверка',StopRequested:'Запрошена остановка',ScheduleStorageOrConfigurationInvalid:'Состояние серии или настройки недоступны либо изменены',RunUnavailableOrInvalid:'Не удалось безопасно выполнить запуск'}[reason]??reasons[reason]??reason)}
async function pollSeries(){try{const response=await fetch('/operator/schedule',{cache:'no-store'});if(!response.ok)throw Error();const v=await response.json();el('schedule').hidden=!v.Enabled;if(v.Enabled){seriesToken=v.Token;const s=v.State;const signature=JSON.stringify(s);if(signature!==seriesSignature){seriesSignature=signature;text('series-state',`${v.SeriesId} · ${seriesLabels[s.Status]??s.Status}`);text('series-budget',`Зарезервировано: ${s.ReservedRuns}/${v.Limits.MaxRuns} запусков · ${s.ReservedActions}/${v.Limits.MaxTotalActions} действий · ${s.ReservedDecisions}/${v.Limits.MaxTotalDecisions} решений · ${s.ReservedSeconds}/${v.Limits.MaxTotalSeconds} сек`);text('series-next',s.Status==='Waiting'?`Следующий запуск: ${new Date(s.NextDue).toLocaleString()} · окончание серии: ${new Date(v.Limits.ExpiresUtc).toLocaleString()}`:`Причина: ${seriesReason(s.Reason)}`);el('series-stop').disabled=['Completed','Stopped','InterventionRequired'].includes(s.Status);el('series-events').replaceChildren();for(const n of s.Notifications){const li=document.createElement('li');li.dataset.id=n.Id;li.textContent=`${new Date(n.At).toLocaleString()} · ${seriesLabels[n.Kind]??n.Kind} · ${n.RunId??v.SeriesId} · ${seriesReason(n.Reason)}`;el('series-events').append(li)}}}}catch{if(!el('schedule').hidden)text('series-result','Не удалось обновить состояние серии.')}finally{setTimeout(pollSeries,3000)}}
el('series-stop').onclick=async()=>{try{const response=await fetch('/operator/schedule/stop',{method:'POST',headers:{'X-Artiact-Control':seriesToken}});text('series-result',response.ok?'Остановка серии запрошена. Дождитесь сохранённого результата.':'Остановка отклонена.')}catch{text('series-result','Результат запроса остановки неизвестен.')}};
setTimeout(pollSeries,0);
const text=(id,value)=>{el(id).textContent=value??'—'};
const labels={Running:'Исполняется',Idle:'Нет активного запуска',AwaitingRecovery:'Ожидает восстановления',Completed:'Цель достигнута',Stopped:'Штатно остановлен',Blocked:'Требуется вмешательство',UnknownOutcome:'Результат неизвестен',Cancelled:'Остановлен оператором'};
const facts={name:'Имя',hp:'HP',max_hp:'Максимум HP',level:'Уровень',xp:'XP',max_xp:'XP до уровня',map_id:'Карта',x:'X',y:'Y',inventory_max_items:'Вместимость',mining_level:'Добыча · уровень',mining_xp:'Добыча · XP',woodcutting_level:'Рубка · уровень',woodcutting_xp:'Рубка · XP',fishing_level:'Рыбалка · уровень',fishing_xp:'Рыбалка · XP',alchemy_level:'Алхимия · уровень',alchemy_xp:'Алхимия · XP'};
function list(id,entries){el(id).replaceChildren();for(const [key,value] of entries){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=facts[key]??key;dd.textContent=value;el(id).append(dt,dd)}if(!entries.length){const dt=document.createElement('dt');dt.textContent='Данные отсутствуют';el(id).append(dt)}}
const reasons={AutonomousBudgetExhausted:'Достигнут предел запуска',BudgetExhausted:'Бюджет исчерпан',NoUsefulSupportedGoals:'Поддерживаемые цели исчерпаны',TargetsReached:'Заданные цели достигнуты',CheckpointUnavailableOrInvalid:'Не удалось прочитать или сохранить состояние',ExecutionFailed:'Технический отказ исполнения',Cancelled:'Остановка подтверждена',UnresolvedOutcome:'Результат команды не удалось установить',DispatchOutcomeUnknown:'Ответ на команду не подтверждён',NoFeasibleCandidate:'Нет доступной поддерживаемой цели',ObservationFailed:'Не удалось обновить наблюдение',StaleObservation:'Наблюдение устарело',ResourceBudgetExhausted:'Лимит расхода запасов исчерпан'};
function render(v){const r=v.Run;currentRun=r;text('connection','Хост доступен');text('executor',labels[v.Executor]??v.Executor);text('reason',(reasons[r?.Reason]??r?.Reason)??(v.Storage==='Unavailable'?'Хранилище недоступно':v.Storage==='NotConfigured'?'Каталог запусков не настроен':'Нет терминальной причины'));
text('run-id',r?.RunId);text('freshness',`${{Fresh:'Свежие данные',Stale:'Устаревшие данные',Unavailable:'Свежесть неизвестна'}[v.Freshness]}${v.ObservedAt?' · '+new Date(v.ObservedAt).toLocaleString():''}`);
text('actions',r?`${r.UsedActions} / ${r.MaxActions??'неизвестно'}`:'—');text('time',r?.RemainingSeconds==null?'Неизвестно':Math.floor(r.RemainingSeconds)+' сек');text('cooldown',r?r.VerifiedCooldownSeconds+' сек':'—');text('timing',r?.TimingComplete?'Ожидания подтверждены':'Покрытие времени неполное');text('goal',r?.Goal??'Нет активной цели');text('origin',r?.Origin==='Autonomous'?'Автоматически обнаруженная цель':r?'Настроенная цель':'—');text('explanation',r?.Explanation?`Полезность открытия: ${r.Explanation.UnlockUtility}; прогресса: ${r.Explanation.ProgressUtility}`:'Объяснение текущей цели отсутствует');text('last-action',r?.LastConfirmedAction??'Нет подтверждённых действий');text('pending',r?.PendingCommand?'Незавершённая команда: '+r.PendingCommand:'');
list('character',Object.entries(r?.Character??{}));list('resources',Object.entries(r?.ChargedResources??{}));el('milestones').replaceChildren();for(const m of r?.Milestones??[]){const li=document.createElement('li');li.textContent=`${m.Skill} → ${m.Target} · ${m.Outcome}`;el('milestones').append(li)}if(!el('milestones').children.length){const li=document.createElement('li');li.textContent='История отсутствует';el('milestones').append(li)}el('history').replaceChildren();for(const h of v.History??[]){const row=document.createElement('div');row.textContent=`${h.RunId??'Без RunId'} · ${labels[h.Status]??h.Status} · ${h.UsedActions} действий · ${h.VerifiedCooldownSeconds} сек cooldown`;el('history').append(row)}if(!el('history').children.length)text('history','Архив пуст');
const notice=v.Failure?'Технический отказ: '+v.Failure.Operation+' / '+v.Failure.ExceptionType+' ('+v.Failure.ErrorCode+'). Требуется проверка сохранённого состояния.':v.Storage==='Unavailable'?'Сохранённое состояние недоступно. Показанные ранее данные сняты.':r?.InterventionRequired?'Продолжение требует проверки состояния и результата команды.':v.StopRequested?'Остановка запрошена. Подтверждение появится после завершения текущего действия.':null;el('notice').hidden=!notice;text('notice',notice)}
async function poll(){try{const response=await fetch('/operator/snapshot',{cache:'no-store'});if(!response.ok)throw Error();render(await response.json())}catch{text('connection','Связь потеряна');text('freshness','Данные не обновляются');el('notice').hidden=false;text('notice','Хост недоступен. Последние показанные факты могут быть устаревшими.')}finally{setTimeout(poll,3000)}}poll();
let controlToken=null,receipt=null,currentRun=null;
const messages={InspectReady:'Inspect готов. Проверьте цель и нажмите «Запустить» до истечения свежести.',StartAccepted:'Запуск принят. Закрытие страницы не остановит исполнителя.',AlreadyAccepted:'Этот запуск уже принят.',StopRequested:'Остановка запрошена. Дождитесь подтверждения.',ExecutorIdle:'Исполнитель уже остановлен.',Archived:'Итог сохранён в архиве.',InspectExpired:'Inspect устарел. Выполните проверку повторно.',InspectRequired:'Сначала выполните Inspect.',ExecutorBusy:'Исполнитель занят.',StartRefused:'Старт отклонён: проверьте права, состояние и владение персонажем.',ExistingRunIdentityMismatch:'Существует другой запуск. Восстановите его или архивируйте проверенный итог.',ArchiveRefused:'Архивирование запрещено: итог не подтверждён или требует вмешательства.',ProfileUnavailableOrInvalid:'Профиль или лимиты недоступны. Проверьте настройки.'};
function request(){return{RunId:el('input-run').value,MaxActions:Number(el('input-actions').value),MaxSeconds:Number(el('input-seconds').value),MaxDecisions:Number(el('input-decisions').value),MaxNoProgress:Number(el('input-no-progress').value)}}
function fill(p){text('control-result','Выполните свежий Inspect перед стартом.');receipt=null;el('start').disabled=true;el('input-run').value=p.RunId??'';el('input-actions').value=p.MaxActions;el('input-seconds').value=p.MaxSeconds;el('input-decisions').value=p.MaxDecisions;el('input-no-progress').value=p.MaxNoProgress}
async function command(path,body){const response=await fetch('/operator/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-Artiact-Control':controlToken},body:JSON.stringify(body??{})});if(response.status===403)throw Error('Доступ отклонён. Обновите страницу.');const result=await response.json();text('control-result',messages[result.Reason]??result.Reason);return result}
async function guarded(action){try{await action()}catch(error){text('control-result',error.message??'Запрос не подтверждён. Проверьте состояние запуска.')}}
el('prepare').addEventListener('input',()=>{receipt=null;el('start').disabled=true});
el('prepare').addEventListener('submit',event=>{event.preventDefault();guarded(async()=>{el('inspect').disabled=true;try{const result=await command('inspect',request());receipt=result.Accepted?result.Receipt:null;el('start').disabled=!receipt;if(result.Decision)text('control-result',(messages[result.Reason]??result.Reason)+' Цель: '+(result.Decision.Candidate??'—')+'; команда: '+(result.Decision.Command??'—'))}finally{el('inspect').disabled=false}})});
el('start').addEventListener('click',()=>guarded(async()=>{el('start').disabled=true;await command('start',{Receipt:receipt})}));
el('stop').addEventListener('click',()=>guarded(()=>command('stop')));
el('archive').addEventListener('click',()=>guarded(async()=>{if(!currentRun?.IdentityDigest)throw Error('Нет сохранённого запуска.');await command('archive',{IdentityDigest:currentRun.IdentityDigest})}));
el('recover').addEventListener('click',()=>{if(!currentRun?.RunId){text('control-result','Нет сохранённого RunId.');return}fill(currentRun)});
el('new-run').addEventListener('click',()=>{el('input-run').value='run-'+crypto.randomUUID();receipt=null;el('start').disabled=true;text('control-result','Новый RunId подготовлен. Существующий запуск не изменён.')});
async function loadControls(){try{const response=await fetch('/operator/controls',{cache:'no-store'});if(!response.ok)return;const value=await response.json();if(!value.Enabled)return;controlToken=value.Token;el('controls').hidden=false;const p=value.Profile;fill({...p.Limits,RunId:p.Limits.RunId||'run-'+crypto.randomUUID()});for(const [id,key] of [['input-actions','MaxActions'],['input-seconds','MaxSeconds'],['input-decisions','MaxDecisions'],['input-no-progress','MaxNoProgress']])el(id).max=p.Limits[key];text('permissions',`Персонаж: ${p.Character}. Игровые действия: ${p.AllowActions?'разрешены настройками':'выключены'}. Профиль: ${p.AutonomousGoals?'автоматические цели':'заданные цели'}.`);text('profile',JSON.stringify(p,null,2))}catch{text('control-result','Не удалось загрузить управление.')}}loadControls();
