const el=id=>document.getElementById(id);
const text=(id,value)=>{el(id).textContent=value??'—'};
const labels={Running:'Исполняется',Idle:'Нет активного запуска',AwaitingRecovery:'Ожидает восстановления',Completed:'Цель достигнута',Stopped:'Штатно остановлен',Blocked:'Требуется вмешательство',UnknownOutcome:'Результат неизвестен',Cancelled:'Остановлен оператором'};
const facts={name:'Имя',hp:'HP',max_hp:'Максимум HP',level:'Уровень',xp:'XP',max_xp:'XP до уровня',map_id:'Карта',x:'X',y:'Y',inventory_max_items:'Вместимость',mining_level:'Добыча · уровень',mining_xp:'Добыча · XP',woodcutting_level:'Рубка · уровень',woodcutting_xp:'Рубка · XP',fishing_level:'Рыбалка · уровень',fishing_xp:'Рыбалка · XP',alchemy_level:'Алхимия · уровень',alchemy_xp:'Алхимия · XP'};
function list(id,entries){el(id).replaceChildren();for(const [key,value] of entries){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=facts[key]??key;dd.textContent=value;el(id).append(dt,dd)}if(!entries.length){const dt=document.createElement('dt');dt.textContent='Данные отсутствуют';el(id).append(dt)}}
const reasons={AutonomousBudgetExhausted:'Достигнут предел запуска',BudgetExhausted:'Бюджет исчерпан',NoUsefulSupportedGoals:'Поддерживаемые цели исчерпаны',TargetsReached:'Заданные цели достигнуты',CheckpointUnavailableOrInvalid:'Не удалось прочитать или сохранить состояние',ExecutionFailed:'Технический отказ исполнения',Cancelled:'Остановка подтверждена',UnresolvedOutcome:'Результат команды не удалось установить',DispatchOutcomeUnknown:'Ответ на команду не подтверждён',NoFeasibleCandidate:'Нет доступной поддерживаемой цели',ObservationFailed:'Не удалось обновить наблюдение',StaleObservation:'Наблюдение устарело',ResourceBudgetExhausted:'Лимит расхода запасов исчерпан'};
function render(v){const r=v.Run;text('connection','Хост доступен');text('executor',labels[v.Executor]??v.Executor);text('reason',(reasons[r?.Reason]??r?.Reason)??(v.Storage==='Unavailable'?'Хранилище недоступно':v.Storage==='NotConfigured'?'Каталог запусков не настроен':'Нет терминальной причины'));
text('run-id',r?.RunId);text('freshness',`${{Fresh:'Свежие данные',Stale:'Устаревшие данные',Unavailable:'Свежесть неизвестна'}[v.Freshness]}${v.ObservedAt?' · '+new Date(v.ObservedAt).toLocaleString():''}`);
text('actions',r?`${r.UsedActions} / ${r.MaxActions??'неизвестно'}`:'—');text('time',r?.RemainingSeconds==null?'Неизвестно':Math.floor(r.RemainingSeconds)+' сек');text('cooldown',r?r.VerifiedCooldownSeconds+' сек':'—');text('timing',r?.TimingComplete?'Ожидания подтверждены':'Покрытие времени неполное');text('goal',r?.Goal??'Нет активной цели');text('origin',r?.Origin==='Autonomous'?'Автоматически обнаруженная цель':r?'Настроенная цель':'—');text('explanation',r?.Explanation?`Полезность открытия: ${r.Explanation.UnlockUtility}; прогресса: ${r.Explanation.ProgressUtility}`:'Объяснение текущей цели отсутствует');text('last-action',r?.LastConfirmedAction??'Нет подтверждённых действий');text('pending',r?.PendingCommand?'Незавершённая команда: '+r.PendingCommand:'');
list('character',Object.entries(r?.Character??{}));list('resources',Object.entries(r?.ChargedResources??{}));el('milestones').replaceChildren();for(const m of r?.Milestones??[]){const li=document.createElement('li');li.textContent=`${m.Skill} → ${m.Target} · ${m.Outcome}`;el('milestones').append(li)}if(!el('milestones').children.length){const li=document.createElement('li');li.textContent='История отсутствует';el('milestones').append(li)}el('history').replaceChildren();for(const h of v.History??[]){const row=document.createElement('div');row.textContent=`${h.RunId??'Без RunId'} · ${labels[h.Status]??h.Status} · ${h.UsedActions} действий · ${h.VerifiedCooldownSeconds} сек cooldown`;el('history').append(row)}if(!el('history').children.length)text('history','Архив пуст');
const notice=v.Failure?'Технический отказ: '+v.Failure.Operation+' / '+v.Failure.ExceptionType+' ('+v.Failure.ErrorCode+'). Требуется проверка сохранённого состояния.':v.Storage==='Unavailable'?'Сохранённое состояние недоступно. Показанные ранее данные сняты.':r?.InterventionRequired?'Продолжение требует проверки состояния и результата команды.':v.StopRequested?'Остановка запрошена. Подтверждение появится после завершения текущего действия.':null;el('notice').hidden=!notice;text('notice',notice)}
async function poll(){try{const response=await fetch('/operator/snapshot',{cache:'no-store'});if(!response.ok)throw Error();render(await response.json())}catch{text('connection','Связь потеряна');text('freshness','Данные не обновляются');el('notice').hidden=false;text('notice','Хост недоступен. Последние показанные факты могут быть устаревшими.')}finally{setTimeout(poll,3000)}}poll();
